### PR TITLE
Some french updates in app.php file

### PR DESCRIPTION
**Pull request by helgvor-stoll**
## Description
Some correction to the app.php file french translation

### CODE REVIEW

**Comment by navneetbhardwaj** [comment]
@helgvor-stoll

Thank you for your contribution. It looks like the linting and code style tests have failed. To ensure code quality, please run the following commands:

1. **Linting and Code Style Fixes**:

    ```bash
    vendor/bin/pint
    ```

   This will analyze and automatically fix any style issues in your PHP code.

2. **Running Tests**:

    ```bash
    vendor/bin/pest
    ```

   This will execute your test suite to ensure everything is working as expected.

Please let me know if you encounter any issues or need further assistance!

**Comment by navneetbhardwaj** [comment]
@helgvor-stoll No worries, we'll review it and update.

**Comment by helgvor-stoll** [comment]
@navneetbhardwaj Thank you a lot for the mergings.
Kind Regards

**Comment by navneetbhardwaj** [comment]
@helgvor-stoll 
You're very welcome! Thank you for your valuable contribution. We look forward to more contributions from your side in the future.
Thanks

**Comment by helgvor-stoll** [comment]
@navneetbhardwaj :+1:

**Pull request merged**
